### ISSUE TITLE
App crashes when checking permissions

### ISSUE THREAD

**Issue by alfuller16** [loup-v/beacons#4]
App crashes when Beacons.checkStatus is called _only_ when Location Permission is set to "when in use" on device.

```Beacons.checkStatus(permission: new LocationPermission(ios: LocationPermissionIOS.always));```

When Location Permission is set to "Always" or "Never" the call works fine.

**Comment by AndrewPetrovics** [comment]
I'm experiencing the same issue.

**Comment by lukaspili** [comment]
Fixed in 0.1.0.
