### ISSUE TITLE
Never ending console output on android

### ISSUE THREAD

**Issue by alfuller16** [loup-v/beacons#7]
When using the plugin there is a continuous stream of the following output:
```
...
D/ScanRecord( 5830): parseFromBytes
D/ScanRecord( 5830): first manudata for manu ID
D/ScanRecord( 5830): parseFromBytes
D/ScanRecord( 5830): first manudata for manu ID
D/ScanRecord( 5830): parseFromBytes
D/ScanRecord( 5830): first manudata for manu ID
D/ScanRecord( 5830): parseFromBytes
D/ScanRecord( 5830): first manudata for manu ID
D/ScanRecord( 5830): parseFromBytes
D/ScanRecord( 5830): first manudata for manu ID
...
```

This doesn't affect anything but makes debugging anything else extremely difficult.

There is a new output at least every second.

I would love if there is a way to suppress these messages.

**Comment by lukaspili** [comment]
I will add an API to control the log level.
For ref: https://altbeacon.github.io/android-beacon-library/javadoc/index.html

**Comment by lukaspili** [comment]
Added `Beacons.configure()` API.

**Comment by vinceramcesoliveros** [comment]
It still annoys me when I debug my app and Beacons.configure() doesn't work well when used in a function.
